### ISSUE TITLE
Including files

### ISSUE THREAD

**Issue by skallet** [Zenify/DoctrineFixtures#3]
By nelmio/alice specifications you can include others file in section called 'include', but in Zenify/DoctrineFixtures you have to write 'includes'. Maybe support both variants?

Again, I can make PR :))

**Comment by TomasVotruba** [comment]
@skallet I just improved the code base, so it should be easier to get into it.

Do you plan to send PR?

**Comment by TomasVotruba** [comment]
For `*.neon`, I've added support [for both include/includes keywords](https://github.com/Zenify/DoctrineFixtures/commit/af01f1a744194030ad9ae89160eb6d3e253b5340).

In Readme I've mention `include` only, as it is Alice defaults.
