### ISSUE TITLE
Allow symfony/console version ^3.0

### ISSUE THREAD

**Issue by fvozar** [Zenify/DoctrineFixtures#9]
Hi, 

could you please allow dependency for symfony/console also in version ^3.0 ? I wasn't able to install this doctrine fixtures in my project with newest kdyby/doctrine and zenify/doctrine-migrations, because those packages allows console in version 3 and when trying to install fixtures, composer couldn't resolve proper dependencies.

Thank you

**Comment by enumag** [comment]
Done. Can you test it to see if there are any issues?

**Comment by fvozar** [comment]
It seems, that everything is ok. Can you please release new version? I tested dev-master.
